### ISSUE TITLE
[Backend] As a developer, I want to create Network builder inside SDK

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#10]
## Why

At the `survey-sdk`, we will need to prepare the Network builder, so that user can user our SDK to fetch data from remote server.

## Acceptance Criteria

- User Retrofit and OkHttp3 for network request
- When using SDK, developer don't need to setup/import/implement Retrofit/ OkHttp again, but able to setup some configuration like base url, version name, connection timeout via another Singleton class
- Provide log in debug mode
- Expose custom service builder with Retrofit

**Comment by sleepylee** [comment]
I think we will need to provide them from inside 🤔  let's say if a `sample-app` doesn't use Retrofit + OkHttp, they will have to set up the dependency from the beginning again, it is not efficient. Rather, we will manage it internally of the SDK.

You will also need to factor in the json:api parser when working with the response here. Basically, we will take care of the network invoking gracefully; like a standalone solution.

**Comment by doannimble** [comment]
@sleepylee Yes, I meant `sample-app` can setup some basic configuration of networking like base url, connection timeout, version or event get the specific service class from Retrofit. It does not need to import the Retrofit or OkHttp again.
Maybe my typo not clear enough, let me update it.

**Comment by hoangnguyen92dn** [comment]
> When using SDK, user don't need to setup

I think we could replace `user` by `developer`
