### ISSUE TITLE
[Backend] As a developer, I want to create a public SurveyApi inside the SDK

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#11]
## Why

At the `survey-sdk`, we will need to provide public functions that can be used by the developer who is using the SDK.

## Acceptance Criteria

- A Singleton class that provide setup function to initialize the SDK
- Public functions to config the SDK like baseUrl, connection timeout, version, ect..
- Public functions to get list survey and survey detail

**Comment by luongvo** [comment]
@doannimble I'm not clear about this ticket, could you please put more information and reference link into the Why?

**Comment by doannimble** [comment]
@luongvo I updated already, is it clear enough?

**Comment by sleepylee** [comment]
@doannimble : for this one:
`Public functions to get list survey and survey detail` - I think you will need 2 more [Backend] tickets:

`[Backend] As a developer, I can fetch all surveys list`
`[Backend] As a developer, I can fetch a survey detail by id`
