### ISSUE TITLE
[Backend] As a developer, I want to do the refresh token

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#12]
## Why

As the token can be expired and our SDK might not wok in this case . We need to handle refresh token to make sure the SDK work all time.

## Expected Result
An interceptor that can handle Refresh token

**Comment by hoangnguyen92dn** [comment]
> might not wok

work 😅 

Should we handle the max attempts to avoid looping on refresh token? 🤔

**Comment by sleepylee** [comment]
you may not need this in `Phase 1`. The requirement of phase 1 is dead simple, focusing on how to write the Survey SDK properly & publishing it, the `sample-app` can be a dummy as much as possible.

**Comment by doannimble** [comment]
As @sleepylee comment, I will close this issue.
