### ISSUE TITLE
[UI] As a user, I can see the list of surveys names

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#4]
## Why
On the `sample-app`, we need to provide a simple UI that displays Survey data we fetched.

## Acceptance Criteria
- Display a list of Survey names that we fetched from the API.

## Design
n/a; just use a basic list with a normal text view

**Comment by sleepylee** [comment]
```
## Why
On the `sample-app`, we need to provide a simple UI that displays Survey data we fetched.

## Acceptance Criteria
- Display a list of Survey names that we fetched from the API.

## Design
n/a; just use a basic list with a normal text view
```

**Comment by sleepylee** [comment]
similar: suggesting title update to `[UI] As a user, I can see the list of surveys names`
