### ISSUE TITLE
[Integrate] As a user, I can see list survey after login successfully

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#7]
## Why

Provide a simple List Survey UI that allows user to fetch list survey from SDK.

## Acceptance Criteria
- Once logged in successfully, the `sample-app` should navigate to list survey screen
- When the data loaded successfully, a list of survey with name should be shown

**Comment by luongvo** [comment]
@doannimble 1 small format issue ☝️
