### ISSUE TITLE
[Integrate] As a user, I can see the survey detail

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#8]
## Why
Provide a simple survey detail UI that allows user to fetch a survey from SDK.

## Acceptance Criteria
- Using the getSurveyById() function provided from the SDK to fetch the detail
- Display the survey detail (id, name, title, coverImageUrl) simply in text view + image view.

## Design
n/a, just two simple text view and image view as background

**Comment by sleepylee** [comment]
the Acceptance Criteria can be clear a bit more:
```
- Using the getSurveyById() function provided from the SDK to fetch the detail
- Display the survey detail (id, name, title, coverImageUrl) simply in text view + image view.
```
