### ISSUE TITLE
[Backend] As a developer, I can use the Survey entity

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#9]
## Why
At the `survey-sdk`, we will need to prepare `Survey` model that can be used by the developer who is using the SDK.

## Acceptance Criteria
- Create the Survey entity with the attributes mapped from the API response.
- Expose those entities to the public usage

**Comment by sleepylee** [comment]
```
[Backend] As a developer, I can use the Survey entity

## Why
At the `survey-sdk`, we will need to prepare `Survey` model that can be used by the developer who is using the SDK.

## Acceptance Criteria
- Create the Survey entity with the attributes mapped from the API response.
- Expose those entities to the public usage

**Comment by sleepylee** [comment]
as you can see, I suggested using a different point of view when writing the title here: `As a developer`.
You may guess why. When we target to implement something at the SDK level, it means our product is the SDK and the user will be 'developer', hence, when we write the ticket with the user's expectation, it means the developer's expectation. The title reflects the point of view accordingly.
